apiVersion: v1
kind: Service
metadata:
  name: moodle
  labels:
    app: moodle
spec:
  ports:
    - port: 80
  selector:
    app: moodle
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: m-pv-claim
  labels:
    app: moodle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
  labels:
    app: moodle
spec:
  selector:
    matchLabels:
      app: moodle
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: moodle
        tier: frontend
    spec:
      containers:
      - image: moodle:latest
        name: moodle
        env:
        - name: MOODLE_DB_HOST
          value: mooodle-mysql
        - name: MOODLE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: moodle
        volumeMounts:
        - name: moodle-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: moodle-persistent-storage
        persistentVolumeClaim:
          claimName: m-pv-claim
